import { Pitch } from '../types';

export const PITCHES: Pitch[] = [
  {
    id: '1',
    name: '5-son maktab',
    distance: '1.2 km',
    format: '5v5',
    surface: 'AstroTurf',
    type: 'outdoor',
    pricePerHour: 120,
    rating: 4.9,
    reviewCount: 128,
    isActive: true,
    instantBook: true,
    image: '⚽',
    imageUrl: 'https://images.unsplash.com/photo-1529900748604-07564a03e7a6?w=800&q=80',
    address: 'Lenin, Urganch',
  },
  {
    id: '2',
    name: 'Xorazm fc',
    distance: '0.8 km',
    format: '5v5',
    surface: 'Grass',
    type: 'indoor',
    pricePerHour: 80,
    rating: 4.7,
    reviewCount: 95,
    isActive: true,
    instantBook: false,
    image: '🏟️',
    imageUrl: 'https://images.unsplash.com/photo-1551958219-acbc595d6943?w=800&q=80',
    address: 'Marifatchilar, Yangiariq',
  },
  {
    id: '3',
    name: 'ProField Arena',
    distance: '2.1 km',
    format: '5v5',
    surface: 'Synthetic',
    type: 'indoor',
    pricePerHour: 60,
    rating: 4.5,
    reviewCount: 67,
    isActive: false,
    instantBook: false,
    image: '🥅',
    imageUrl: 'https://images.unsplash.com/photo-1459865264687-595d652de67e?w=800&q=80',
    address: 'Mirzo Ulugbek, Toshkent',
  },
  {
    id: '4',
    name: 'Rooftop Tennis Club',
    distance: '3.4 km',
    format: '1v1',
    surface: 'Hard Court',
    type: 'outdoor',
    pricePerHour: 45,
    rating: 4.8,
    reviewCount: 210,
    isActive: true,
    instantBook: true,
    image: '🎾',
    imageUrl: 'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?w=800&q=80',
    address: 'Shayxontohur, Toshkent',
  },
];

export const FILTERS = ['All Venues', '5-a-side', '7-a-side', 'Indoor', 'Tennis'];